
package chapter1

/**
*@author Fer Carraro
*@date 03/septiembre/2019
*/

fun excepcionTestA():Unit{
    try {
      println()
    }
    catch (e: Exception) {
        println("Alguna Exception ha ocurrido")
    }
    finally {
    
    }

}
